In [1]:
import numpy as np

In [2]:
np.empty()

TypeError: empty() missing required argument 'shape' (pos 0)

In [3]:
np.empty(2) # It will create a empty array from heap section of the memory

array([4.04272379e-166, 1.31477152e+066])

In [6]:
a = np.empty((3,3)) #Inside the arguments it can be a integer or a tuple.

In [7]:
a

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 8.656e-321],
       [0.000e+000, 0.000e+000, 5.682e-322]])

In [8]:
a.shape

(3, 3)

In [9]:
a = np.array([1,2,3,4,4,6,7,1,2,4,6,7,1])

In [10]:
np.unique(a) # will return the unique elemnts in the array

array([1, 2, 3, 4, 6, 7])

In [11]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4, 6, 7]), array([3, 2, 1, 3, 2, 2], dtype=int64))

# 2D Array

In [12]:
b = np.array([[1,2,3]])

In [14]:
b.shape

(1, 3)

In [15]:
b.ndim

2

In [16]:
c= np.array([[1,2,3],[4,5,6]])

In [17]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c.ndim

2

In [19]:
c.shape

(2, 3)

In [23]:
d= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
e = np.array([[1],[2],[3],[4],[5]])

In [26]:
e.shape

(5, 1)

In [27]:
len(e) # len(e) = e.shape[0]

5

In [29]:
a = np.array([1,2,3])
b = np.array([0,4,2])
a >= b

array([ True, False,  True])

In [30]:
a = np.array([0,1,2,3,4,5])
mask= (a%2 == 0)
a[mask] = -1

In [31]:
a

array([-1,  1, -1,  3, -1,  5])

**Reshape**

In [32]:
a = np.arange(1,13)
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
a.reshape(3,4) # multiplication of Rows & Columns should match with the len of the array or with shape of the array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
a.reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [36]:
a.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
a.reshape(2,2,3).ndim

3

**Transpose of a Matrix**

In [38]:
b = a.reshape(3,4)

In [39]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
b.shape

(3, 4)

In [44]:
c = b.T # .T is used for transpose

In [45]:
c

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [46]:
c.shape

(4, 3)

In [47]:
t = np.arange(1,13).reshape(3,4)

In [48]:
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
t.flatten() #It converts to 1-D array from 2-D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**Indexing and Slicing**

In [50]:
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
t[0]

array([1, 2, 3, 4])

In [52]:
t[0][1] # Not recommended

2

In [53]:
t[0,1] #Recommended

2

In [54]:
t[-3,-3] #Negative Indexing

2

In [55]:
t[[1,0,2]] #Re-arranging or shuffling the rows

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [56]:
t[[1,0,2],[1,3,3]]

array([ 6,  4, 12])

**Slicing**

In [57]:
t[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
t[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [59]:
t[::-1, ::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

**Masking in 2-D**

In [60]:
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
 t < 6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [64]:
t[t<6]

array([1, 2, 3, 4, 5])

In [65]:
t[(t<5) & (t>8)]

array([], dtype=int32)

In [66]:
t[(t<5) | (t>8)]

array([ 1,  2,  3,  4,  9, 10, 11, 12])

**Universal Functions on 2D**

In [67]:
np.sum(t)

78

In [68]:
np.sum(t,axis=0) #In the vertical Direction, sum of all elements
''' 1+5+9 = 15, 2+6+10 = 18,.....'''

array([15, 18, 21, 24])

In [69]:
np.min(t,axis = 0) # In the vertical direction, min value. In the 1st vertical it is 1
#In the 2nd vertical it is 2 and so on


array([1, 2, 3, 4])

In [70]:
np.mean(t,axis=0)

array([5., 6., 7., 8.])

In [71]:
np.median(t,axis=0)

array([5., 6., 7., 8.])

**Sort and Argsort**

In [73]:
b=np.array([[5,8,2,7],[9,5,8,0],[2,6,20,30],[7,2,8,1]])
b

array([[ 5,  8,  2,  7],
       [ 9,  5,  8,  0],
       [ 2,  6, 20, 30],
       [ 7,  2,  8,  1]])

In [74]:
np.sort(b) #Within each row, elements will be sorted.

array([[ 2,  5,  7,  8],
       [ 0,  5,  8,  9],
       [ 2,  6, 20, 30],
       [ 1,  2,  7,  8]])

In [75]:
np.sort(b,axis = 1) # Sorting done in Horizontal

array([[ 2,  5,  7,  8],
       [ 0,  5,  8,  9],
       [ 2,  6, 20, 30],
       [ 1,  2,  7,  8]])

In [76]:
np.sort(b,axis = 0) #Sorting done on Vertical

array([[ 2,  2,  2,  0],
       [ 5,  5,  8,  1],
       [ 7,  6,  8,  7],
       [ 9,  8, 20, 30]])

In [77]:
np.argsort(b) #Returning the indexes of the elements of the actual matrix

array([[2, 0, 3, 1],
       [3, 1, 2, 0],
       [0, 1, 2, 3],
       [3, 1, 0, 2]], dtype=int64)

In [78]:
np.argsort(b, axis = 1) 

array([[2, 0, 3, 1],
       [3, 1, 2, 0],
       [0, 1, 2, 3],
       [3, 1, 0, 2]], dtype=int64)

In [79]:
np.argsort(b, axis = 0) 

array([[2, 3, 0, 1],
       [0, 1, 1, 3],
       [3, 2, 3, 0],
       [1, 0, 2, 2]], dtype=int64)

In [80]:
b

array([[ 5,  8,  2,  7],
       [ 9,  5,  8,  0],
       [ 2,  6, 20, 30],
       [ 7,  2,  8,  1]])

In [81]:
np.argmin(b,axis=0)

array([2, 3, 0, 1], dtype=int64)