In [1]:
import sys as s

In [2]:
s.getsizeof(1) #Integer

28

In [3]:
s.getsizeof('Python') #String

55

In [4]:
s.getsizeof('') #null

49

In [5]:
s.getsizeof('P')

50

In [6]:
s.getsizeof('Py')

51

In [7]:
s.getsizeof([]) #Empty List

56

In [8]:
s.getsizeof([1]) #Incremented by 8

64

In [9]:
s.getsizeof([1,2]) 

72

In [10]:
s.getsizeof([1,2,3]) 

88

In [11]:
lis = [1, 'python', 'Raviteja', 'Nowduru'] #Heterogenous data still since the no.of elemnts are 4, size is 88

In [12]:
s.getsizeof(lis)

88

In [13]:
s.getsizeof([1,2,[3,4],[1,2,3,4,5]]) # 1,2, [3,4], [1,2,3,4,5] are a total of 4 elements though there are 9 elements in total

88

# NUMPY  2

In [15]:
list1 = [1,2,3,4,5,6]
list2 = [10,9,8,7,6,5]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 10, 9, 8, 7, 6, 5]


In [16]:
print(list1*list2)

TypeError: can't multiply sequence by non-int of type 'list'

In [17]:
import numpy as np

In [18]:
n1 = np.array(list1)
n2 = np.array(list2)

In [19]:
print(n1*n2)

[10 18 24 28 30 30]


In [20]:
n3 = np.array([1,2,3,4,5])

In [21]:
print(n1*n3)

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [22]:
print(n1+n3)

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [23]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8])
a[2:] = b[::-1]
a

array([1, 2, 8, 7, 6])

In [24]:
c = np.array([1,2,3,4,5,9])
d = np.array([6,7,8])
c[2:] = d[::-1]
c

ValueError: could not broadcast input array from shape (3,) into shape (4,)

What is the difference? A size of 3 is being tried to fit into the size of 4.

In [25]:
c = np.array([1,2,3,4])
d = np.array([6,7,8])
c[2:] = d[::-1]
c

ValueError: could not broadcast input array from shape (3,) into shape (2,)

Here 3 elemnts are being tried to fit into the size of 2 elements. 

In [61]:
a = np.array(range(0,11))

In [62]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
mask = a< 6

In [30]:
mask

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [32]:
a[mask]

array([0, 1, 2, 3, 4, 5])

In [33]:
mask = a% 2 == 0

In [34]:
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [35]:
a[mask]

array([ 0,  2,  4,  6,  8, 10])

In [37]:
a[a%2 == 1]

array([1, 3, 5, 7, 9])

In [69]:
mask1 = a% 2 == 0

In [70]:
mask2 = a% 5 == 0

In [65]:
a[mask1 | mask2]

array([ 0,  2,  4,  5,  6,  8, 10])

In [66]:
a[mask1 & mask2]

array([ 0, 10])

In [47]:
a[mask1 & mask2] = -1
a

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, -1])

In [82]:
a[mask1 & mask2] *= -1


In [83]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, -10])

In [85]:
a = np.arange(11)
b = np.arange(11)

In [86]:
a + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [13]:
!pip install gdown

Defaulting to user installation because normal site-packages is not writeable


In [14]:
!gdown 14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8

Downloading...
From: https://drive.google.com/uc?id=14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8
To: C:\Users\ravit\Scaler\Data Analytics and Visualizations(DAV-1)\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|##########| 2.55k/2.55k [00:00<?, ?B/s]


In [17]:
import numpy as np


In [26]:
score = np.loadtxt("D:\DAV-1\Lecture-2\survey.txt", dtype="int")

In [27]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [28]:
score.shape

(1167,)

In [29]:
score.min()

1

In [30]:
score.max()

10

In [37]:
mask1 = score < 7

In [38]:
sum(mask1)

332

In [47]:
detractor = score[mask1]

In [48]:
detractor.shape

(332,)

In [49]:
detractor_count = detractor.shape[0]

In [50]:
detractor_count

332

In [44]:
sum((score >= 7) & (score < 9))

226

In [51]:
mask_promoter = (score == 9) | (score == 10)

In [52]:
promoter = score[mask_promoter]

In [53]:
promoter.shape

(609,)

In [54]:
promoter_number = promoter.shape[0]

In [55]:
promoter_number

609

In [56]:
total_count_of_customers = score.shape[0]

In [57]:
total_count_of_customers

1167

In [58]:
nps = 100 * (promoter_number - detractor_count )/ total_count_of_customers

In [60]:
round(nps,2)

23.74