In [1]:
import numpy as np
a = np.arange(4)

In [2]:
a

array([0, 1, 2, 3])

In [3]:
b = a.reshape((2,2))
b

array([[0, 1],
       [2, 3]])

Shallow Copy

In [4]:
#Shallow copy is when you are not creating a new memory block
#When you are creating new memory block it is called deep copy

In [5]:
a[0]= 1000
a

array([1000,    1,    2,    3])

In [6]:
b

array([[1000,    1],
       [   2,    3]])

In [7]:
np.shares_memory(a,b) #Whether both a and b share same locations

True

In [8]:
a = np.arange(4)
a

array([0, 1, 2, 3])

Deep Copy

In [9]:
c = a+2
c
#It is deep copy. In deep copy a new memory block is created. When any operation is performed on the previously created 
#array it will be a deep copy.
# In shallow copy only attributes will performed.
# So in layman's terms, using attributes --> Shallow Copy, Using operations --> Deep Copy

array([2, 3, 4, 5])

In [10]:
a[0]= 100
a

array([100,   1,   2,   3])

In [11]:
c

array([2, 3, 4, 5])

In [12]:
np.shares_memory(a,c)

False

2nd Method of creating a Shallow Copy

In [13]:
d = a.view()
d

array([100,   1,   2,   3])

In [14]:
np.shares_memory(a,d)

True

2nd Method of creating a Deep Copy 

In [15]:
e = a.copy()

In [16]:
np.shares_memory(a,e)

False

In [17]:
# There are times when .copy() will not work.

In [18]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b = a.copy()

In [20]:
c = np.array([1,'m',[1,2,3]], dtype = object)
c

array([1, 'm', list([1, 2, 3])], dtype=object)

In [21]:
d = c.copy()

In [22]:
c[2][0] = 100

In [23]:
c

array([1, 'm', list([100, 2, 3])], dtype=object)

In [24]:
np.shares_memory(c,d)

False

In [25]:
d 
#Here deep copy using .copy() will not work. But the values are getting reflected in both arrays
# using deep method and working like shallow copy

array([1, 'm', list([100, 2, 3])], dtype=object)

In [26]:
import copy
d = copy.deepcopy(c)

In [27]:
c

array([1, 'm', list([100, 2, 3])], dtype=object)

In [28]:
d

array([1, 'm', list([100, 2, 3])], dtype=object)

In [29]:
c[2][0] = 200

In [30]:
c

array([1, 'm', list([200, 2, 3])], dtype=object)

In [31]:
d

array([1, 'm', list([100, 2, 3])], dtype=object)

In [32]:
np.shares_memory(c,d)

False

Dimension Expansion and Reduction

In [33]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
b = a.reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
b.shape

(3, 3)

In [36]:
c = a.reshape((3,3,1))

In [37]:
d = a.reshape((3,3,1,1,1,1,1))

In [38]:
#n dimenssions can be created 3 x 3 = 9, so next axis can be 1 , 1,1...

In [39]:
a = np.arange(9)
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8]
(9,)


In [40]:
e = np.expand_dims(a, axis=0) # Add a dimn on left, axis =0

In [41]:
e

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [42]:
e.shape

(1, 9)

In [43]:
e = np.expand_dims(a, axis=1)
print(e)
print(e.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(9, 1)


In [44]:
a = np.arange(1,13).reshape((3,4))

In [45]:
print(a.shape)

(3, 4)


In [46]:
b = np.expand_dims(a,axis = 2)
b

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [47]:
a = np.arange(5)
a[:, np.newaxis].shape

(5, 1)

In [48]:
a[ np.newaxis,:].shape

(1, 5)

In [49]:
np.array(np.arange(10).reshape(2,5),ndmin=10).shape

(1, 1, 1, 1, 1, 1, 1, 1, 2, 5)

In [50]:
a = np.arange(1,13).reshape(1,3,1,4,1)

In [51]:
a.shape

(1, 3, 1, 4, 1)

In [52]:
np.squeeze(a).shape #Removing all 1's in one go.

(3, 4)

#Array Split and Merge

In [65]:
a = np.arange(1,13)

In [66]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
np.split(a,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [69]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [70]:
np.split(a,5) #Since there are 12 elements, it can't be divided by 5 equal parts

ValueError: array split does not result in an equal division

In [71]:
np.split(a,[4,5]) # 0 to 4, 4 to 5, 5 uptill end 

[array([1, 2, 3, 4]), array([5]), array([ 6,  7,  8,  9, 10, 11, 12])]

In [72]:
np.split(a,[4,5,7])

[array([1, 2, 3, 4]), array([5]), array([6, 7]), array([ 8,  9, 10, 11, 12])]

In [73]:
np.split(a,[4,5,7,5]) # 0 to 4 index(index 4 will be excluded), 4 to 5(5th index element exluded, 
#5 to 7(7th index element excluded. After that it will not be return back to 5 so it will a empty list. 
# last 5 in the above code will make it run from 5th element uuptill end of the array. which will be [6,7,8,9,10,11,12]


[array([1, 2, 3, 4]),
 array([5]),
 array([6, 7]),
 array([], dtype=int32),
 array([ 6,  7,  8,  9, 10, 11, 12])]

Splitting 2D Array

In [74]:
a = np.arange(1,13).reshape(3,4)

In [75]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
np.split(a,2,axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [79]:
np.split(a,3,axis = 0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [80]:
np.vsplit(a,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [81]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [82]:
a = np.arange(1,5)
b = np.arange(5,9)

In [83]:
a 

array([1, 2, 3, 4])

In [84]:
b

array([5, 6, 7, 8])

In [86]:
np.hstack((a,b)) #Result is a 1D Array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
np.hstack((a,b)).shape

(8,)

In [89]:
np.vstack((a,b)) #result is a 2D Array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
np.vstack((a,b)).shape

(2, 4)

In [93]:
a = np.arange(1,13).reshape(3,4)
b =  np.arange(1,13).reshape(3,4)

In [92]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [96]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
np.hstack((a,b)).shape

(3, 8)

In [98]:
np.vstack((a,b)).shape

(6, 4)

In [101]:
a = np.arange(1,13).reshape(3,4)
b =  np.arange(1,17).reshape(4,4)

In [102]:
np.hstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [103]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [104]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
np.tile(a,(3,2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])