In [1]:
import sys as s
s.getsizeof(1) #integer

28

In [2]:
s.getsizeof('Python') #string

55

In [3]:
s.getsizeof('')

49

In [4]:
s.getsizeof('P')

50

In [5]:
s.getsizeof('Py')

51

In [6]:
s.getsizeof('Pyt')

52

In [7]:
s.getsizeof([])

56

In [8]:
s.getsizeof([1])

64

In [9]:
s.getsizeof([1,2])

72

In [12]:
s.getsizeof([1,2,3])

88

In [13]:
s.getsizeof([1,2,3,4])

88

In [16]:
lis = [1,'Ankit']
s.getsizeof(lis)

72

In [17]:
s.getsizeof([1,2,[3,4,5,1]])

80

NUMPY 2

In [19]:
list1 = [1,2,3,4,5,6]
list2 = [10,9,8,7,6,5]

print(list1*list2)

TypeError: can't multiply sequence by non-int of type 'list'

In [20]:
import numpy as np
a1=np.array(list1)
a2=np.array(list2)

a1*a2

array([10, 18, 24, 28, 30, 30])

In [22]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8])

# a[2:] = b[::-1] 

In [23]:
a

array([1, 2, 3, 4, 5])

In [24]:
b

array([6, 7, 8])

In [25]:
a[2:]

array([3, 4, 5])

In [26]:
b[::-1]

array([8, 7, 6])

In [27]:
a[2:] = b[::-1]
a

array([1, 2, 8, 7, 6])

What is size is diff

In [28]:
a[3:] = b[::-1]

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [29]:
a[1:] = b[::-1]

ValueError: could not broadcast input array from shape (3,) into shape (4,)

In [31]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
mask = a<6
mask

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [33]:
a[mask]

array([0, 1, 2, 3, 4, 5])

In [34]:
mask = a%2 ==0
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [35]:
a[mask]

array([ 0,  2,  4,  6,  8, 10])

In [36]:
mask1 = (a%2 ==0)
mask2 = (a%5 ==0)

a[mask1]

array([ 0,  2,  4,  6,  8, 10])

In [37]:
a[mask2]

array([ 0,  5, 10])

In [38]:
a[mask1 or mask2]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
a[mask1 | mask2]

array([ 0,  2,  4,  5,  6,  8, 10])

In [40]:
a[mask1 & mask2]

array([ 0, 10])

In [41]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a>b

array([False, False, False])

In [42]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [43]:
a+3


array([3, 4, 5, 6])

In [44]:
np.sum(a) #numpy sum

6

In [45]:
a.sum() #ndarray sum

6

In [46]:
np.mean(a)

1.5

In [47]:
6/4

1.5

In [48]:
a.mean()

1.5

In [49]:
np.min(a)

0

In [50]:
np.max(a)

3

In [ ]:
# Use case: Airbnb data 
# We wanted to understand customer sentiment
# Metric : NPS Score

In [51]:
# https://drive.google.com/file/d/14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8/view?usp=sharing

In [53]:
!pip install gdown

In [52]:
!gdown 14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8

Downloading...
From: https://drive.google.com/uc?id=14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8
To: /Users/ritnil/survey.txt
100%|██████████████████████████████████████| 2.55k/2.55k [00:00<00:00, 4.78MB/s]


In [55]:
score = np.loadtxt("/Users/ritnil/survey.txt",dtype="int")
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [56]:
score.shape

(1167,)

In [57]:
score.min()

1

In [58]:
score.max()

10

In [59]:
detractor_mask = (score<7)
detractor_mask

array([False, False,  True, ...,  True, False, False])

In [62]:
detractor = score[detractor_mask]

In [63]:
detractor.shape

(332,)

In [65]:
detractor_number = detractor.shape[0]
detractor_number 

332

In [66]:
total = score.shape[0]
total

1167

In [67]:
promoter_mask = (score>8)
promoter_mask

array([False,  True, False, ..., False,  True,  True])

In [68]:
promoter = score[promoter_mask]
promoter

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [69]:
promoter.shape

(609,)

In [70]:
promoter_number = promoter.shape[0]
promoter_number 

609

In [73]:
percentage_promoter = (promoter_number/total)*100
percentage_promoter

52.185089974293064

In [75]:
percentage_detractor = (detractor_number/total)*100
percentage_detractor

28.449014567266495

In [76]:
nps = percentage_promoter - percentage_detractor
nps

23.73607540702657